### PR TITLE
Support all types of contents

### PR DESCRIPTION
**Pull request by shinnn**
* Currently this plugin only supports buffer contents. But what this plugin does is not depends on which type of contents the files include. So I updated `index.js` to support all types of contents.
* I simplified the test script. fixture/expected files are not necessary for testing.
* I updated some dotfiles.
  * I added `sudo: false` to use [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) on Travis CI.
  * I removed `trailing`, `smarttabs` and `white` options form .jshintrc. [JSHint doesn't support them any longer](https://github.com/jshint/jshint/releases/tag/2.5.0).
* I updated image format of the badges in README form PNG to SVG. SVG badges look beautiful on retina displays.

    | PNG ver. | SVG ver. |
    | ---- | ---- |
    | Build Status | Build Status |

--------------------------------

I'd happily maintain this repo if you want to collaborate me :)

### CODE REVIEW

**Comment by colynb** [comment]
Great contribution to getting this cleaned up... Let me do some testing

**Comment by colynb** [comment]
@shinnn can you write a test for the file streaming option?

**Comment by shinnn** [comment]
@colynb Done. https://github.com/shinnn/gulp-data/commit/ee7bd07223fc6f99df973235c31b808a7d780130

**Comment by colynb** [comment]
All merged @shinnn - super contribution... you've really simplified quite a bit, thank you!

**Comment by shinnn** [comment]
@colynb No problem! Awesome plugin :)

**Pull request merged**
