### PR TITLE
Drop dependency on deprecated `gulp-util`

### LINKED ISSUE #25: Replace deprecated dependency gulp-util
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been recently deprecated. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is one of the most popular packages still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### PR DESCRIPTION
**Pull request by TheDancingCode**
Closes #25

### CODE REVIEW

**Comment by colynb** [comment]
Checking it out now. Thanks!

**Comment by colynb** [comment]
@TheDancingCode is there anything else I need to do on my end to get CI to pass? I'm not sure I fully understand. Thanks.

**Comment by colynb** [comment]
@TheDancingCode nevermind, I found it in the travis yml file

**Comment by colynb** [comment]
@TheDancingCode ok, all updated and a new version was pushed to NPM. Thanks for your help!

**Comment by demurgos** [comment]
Thanks

**Pull request merged**
